# IMPORTANT: After changing a dependency, please run:
# ./gradlew --write-verification-metadata sha256 qa --rerun-tasks

[versions]
lint = "31.13.2"

[libraries]
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-checks = { module = "com.android.tools.lint:lint-checks", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
