# IMPORTANT: After changing a dependency, please run:
# ./gradlew --write-verification-metadata sha256 qa --rerun-tasks

[versions]
androidx-test = "1.5.0"
androidx-test-ext-junit = "1.1.5"
robolectric = "4.10.3"
espresso = "3.4.0"

[libraries]
junit-junit = "junit:junit:4.13.2"
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit" }
androidx-test-orchestrator = "androidx.test:orchestrator:1.4.1"
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0"
robolectric-robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
bouncycastle-bcprov-jdk15on = "org.bouncycastle:bcprov-jdk15on:1.70"
bouncycastle-bcpkix-jdk15on = "org.bouncycastle:bcpkix-jdk15on:1.70"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
square-okhttp-mockserver = "com.squareup.okhttp3:mockwebserver:4.12.0"
mockk = "io.mockk:mockk:1.13.2"
mockk-android = "io.mockk:mockk-android:1.13.2"

conscrypt-openjdk-uber = "org.conscrypt:conscrypt-openjdk-uber:2.5.2"
diff-utils = "io.github.java-diff-utils:java-diff-utils:4.12"
