blank_issues_enabled: false
contact_links:
  - name: ğŸ“ƒSupport Center
    url: https://support.signal.org/
    about: Find answers to many common questions.
  - name: âœ¨ Feature request
    url: https://community.signalusers.org/c/feature-requests/
    about: Missing something in Signal? Let us know.
  - name: ğŸ’¬ Community support
    url: https://community.signalusers.org/c/support/
    about: Feel free to ask anything.
  - name: ğŸ“– Developer documentation
    url: https://signal.org/docs/
    about: Official Signal developer documentation.
  - name: ğŸ“š Translation feedback.
    url: https://community.signalusers.org/c/translation-feedback/
    about: Share feedback on translations.
  - name: â“ Other issue?
    url: https://community.signalusers.org/
    about: Search on the community forums.
