name: Android CI
on:
  pull_request:
  push:
    branches:
    - 'master'
    - '4.**'
    - '5.**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      run: ./gradlew qa
    - name: Upload APK
      if: ${{ github.repository_owner == 'signalapp' }}
      uses: actions/upload-artifact@v2
      with:
        name: Signal-Android-app
        path: app/build/outputs/apk/playProd/debug/Signal-Android-play-prod-arm64-v8a*.apk

  test:
    if: ${{ github.repository_owner == 'signalapp' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Test with Gradle
      run: ./gradlew test
